version: '3'

<<<<<<< HEAD
services:  
  app:    
    build: .    
    ports:      
        - "3000:3000"    
    volumes: 
        - .:/app     
        - /app/node_modules  
    environment:      
          - NODE_ENV=production
=======
services:
  nextjs_app:
    build: .
    container_name: satia_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
>>>>>>> 7802a7b6e9a23e1267cc18796040aaa6c5142b0c
